package main

import (
	"github.com/shkryob/goforum/db"
	"github.com/shkryob/goforum/handler"
	"github.com/shkryob/goforum/router"
	"github.com/shkryob/goforum/store"

	_ "github.com/shkryob/goforum/docs"          // docs is generated by Swag CLI, you have to import it.
	echoSwagger "github.com/swaggo/echo-swagger" // echo-swagger middleware
)

// @title GoForum API
// @version 1.0
// @description GoForum API
// @title GoForum API

// @host 127.0.0.1:1323
// @BasePath /api

// @schemes http https
// @produce	application/json
// @produce	application/xml
// @consumes application/json

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
func main() {
	r := router.New()

	r.GET("/swagger/*", echoSwagger.WrapHandler)

	v1 := r.Group("/api")

	d := db.New()
	db.AutoMigrate(d)

	us := store.NewUserStore(d)
	as := store.NewPostStore(d)
	h := handler.NewHandler(us, as)
	h.Register(v1)
	r.Logger.Fatal(r.Start("127.0.0.1:1323"))
}
